export const DECREMENT = 'counter/DECREMENT';
export const INCREMENT = 'counter/INCREMENT';

export const FETCH_KIT_GENDERS = 'kit/FETCH_KIT_GENDERS';
export const FETCH_KIT_SHOESIZES = 'kit/FETCH_KIT_SHOESIZES';
export const FETCH_KIT_SHIRTSIZES = 'kit/FETCH_KIT_SHIRTSIZES';
export const FETCH_KIT_TOPSIZES = 'kit/FETCH_KIT_TOPSIZES';
export const FETCH_KIT_SHORTSIZES = 'kit/FETCH_KIT_SHORTSIZES';
